# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install --user -r test-requirements.txt
  - pip install -e .
script:
  - python -m unittest discover -s test/ -p 'test_*.py' \
